### ISSUE TITLE
Duplicated email messages

### ISSUE THREAD

**Issue by JC5** [RaymiiOrg/certificate-expiry-monitor#13]
Hi,

I keep getting duplicated messages, like so:

![subd](https://cloud.githubusercontent.com/assets/5889984/14401458/71e46a7c-fe14-11e5-9914-22cfb3f66a24.png)

These four messages represent just two subdomains. I am pretty sure I have not registered for them twice. Do you know what could be the problem?

**Comment by RaymiiOrg** [comment]
Could you send me the domain so that I can check if it's duplicate?

**Comment by JC5** [comment]
I don't know it's been three years I'll see what I can drag up.
