### ISSUE TITLE
database files need to be have a valid json structure

### ISSUE THREAD

**Issue by roock** [RaymiiOrg/certificate-expiry-monitor#14]
during installation of the software I ran into this issue: "Can't read database: 4". I had to create an empty json file with the following content so that the file could be read.

```
{
}
```

maybe related to php7 (my version: PHP 7.0.6)

**Comment by Jormodn** [comment]
Confirm the Issue! My PHP Version is 7.0.20

**Comment by mrtreg** [comment]
Confirmed! (also running PHP 7)

**Comment by giox069** [comment]
Confirmed!
