### ISSUE TITLE
Subscription confirmed has incorrect IP

### ISSUE THREAD

**Issue by jdarwood007** [RaymiiOrg/certificate-expiry-monitor#21]
When I received the confirmation email I got it like this:

> IP
> subscription confirmed from: 108.162.245.224
> 

That happens to be CloudFlare's IP, not mine.

**Comment by stsimb** [comment]
See https://github.com/RaymiiOrg/certificate-expiry-monitor/pull/18 for a fix.

**Comment by jdarwood007** [comment]
I'm sorry, I didn't even look for it.  However this comes from https://certificatemonitor.org/.  Is this the correct place to report it for that site?

**Comment by stsimb** [comment]
This is the code that certificatemonitor.org runs, so @RaymiiOrg ought to see it at some point in time...

**Comment by RaymiiOrg** [comment]
#18 was merged
