### ISSUE TITLE
Cant read database: 4

### ISSUE THREAD

**Issue by Gr1pen** [RaymiiOrg/certificate-expiry-monitor#30]
I am trying to get this working on my own server. When submitting the form after I entered an email-address and domain namn I get the following error:

` Can't read database: 4`

Im no developer myself but my guess is that json_decode is failing. I have tried to add "extension=json.so" on php.ini but no success...

**Comment by qw3r3wq** [comment]
I receive the same error, I use Debian 9.5 + nginx + php7.0-fpm 
`php -m
[PHP Modules]
calendar
Core
ctype
date
exif
fileinfo
filter
ftp
gettext
hash
iconv
json
libxml
mbstring
openssl
pcntl
pcre
PDO
Phar
posix
readline
Reflection
session
shmop
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
Zend OPcache
zlib

[Zend Modules]
Zend OPcache`

**Comment by qw3r3wq** [comment]
I think this is related to issue #14

**Comment by qw3r3wq** [comment]
yes, a suggestion from #14 fixed database error, just insert {} in JSON files.
