### ISSUE TITLE
Not receiving confirmation email

### ISSUE THREAD

**Issue by campodoro74** [RaymiiOrg/certificate-expiry-monitor#32]
Hi! I like this project and setup my own server (https://monitor.zenaconsult.com). I can insert a domain and email address but I'm not receiving any confirmation email. Running Debian 9.3 with Apache and PHP 7.0.27 with the default PHP modules. I have my own email servers; how can I switch to one of those ?

**Comment by biezz** [comment]
我也遇到了相同的问题，可以插入域名和电子邮件，但是不能收到邮件，系统版本是CentOS 7.5，PHP 5.6.38. 我看到了/var/spool/mail/root 提示：
Action: failed
Status: 5.0.0
Remote-MTA: dns; 163mx03.mxmail.netease.com
不知道怎么解决。

**Comment by biezz** [comment]
是否可以有一个关于发送邮件过程的文档？

**Comment by biezz** [comment]
好像设置错了，已经恢复正常。
