### ISSUE TITLE
Nothing after adding a domain

### ISSUE THREAD

**Issue by Rconfoy** [RaymiiOrg/certificate-expiry-monitor#37]
Hi,

Maybe something wrong with my setup.

The initial page loads fine, I add a domain 'mail.xxxx.com' and put in my email and click submit and it goes to the 'mydomain.com/add.php' and doesn't load anything, just shows the page header, no email goes out, no errors from what I can see. I am on the latest release of Debian, running PHP 5.6

Thank you in advance.

**Comment by jdmalibiran** [comment]
I also have the same issue after installing. OS: CentOS 7. PhP 5.6. Anything I missed? Firewall:disabled, SELINUX:disabled

**Comment by Rconfoy** [comment]
All sounds right. Let me know if you find a fix.

**Comment by jdmalibiran** [comment]
I think we are missing something here :(

**Comment by lacertilan** [comment]
Same issue on Ubuntu 18.04.2 LTS using PHP7.2

**Comment by red-erik** [comment]
Same here with Rhel 7.6 and PHP 7. In HTTPS logs I see 500 error

**Comment by red-erik** [comment]
Hello,
in my case the problem was the missing support for PHP function mb_strtolower().
This can be resolved installing php-mbstring (for you version of PHP) or changing email.php line 18 and domains.php line 25 from mb_strtolower() to strtolower().

Red.
