### ISSUE TITLE
Not sending expiration emails

### ISSUE THREAD

**Issue by Beeez** [RaymiiOrg/certificate-expiry-monitor#54]
I am having some issues getting the emails to send when there is an expiring cert. The emails send fine when subscribing to an alert, as well as confirming the addition of the site to monitor, but when checking the logs I am seeing:

```Domain: <redacted>.
Email: <redacted>.
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/html/certificate-expiry-monitor/cron.php on line 55
        Cert Chain #1. Expiry Date: 2020-01-10 20:09:28 UTC. Common Name: <redacted>
                Domain <redacted> expires in 30 days.
PHP Fatal error:  Uncaught Error: Call to undefined function bcmod() in /var/www/html/certificate-expiry-monitor/functions/helpers.php:77
Stack trace:
#0 /var/www/html/certificate-expiry-monitor/functions/certs.php(72): bcdechex('162795447394318...')
#1 /var/www/html/certificate-expiry-monitor/functions/email.php(157): cert_serial(Resource id #432)
#2 /var/www/html/certificate-expiry-monitor/functions/certs.php(159): send_expires_in_email(30, '<redacted>...', '<redacted>...', Resource id #432)
#3 /var/www/html/certificate-expiry-monitor/cron.php(91): cert_expiry_emails('<redacted>...', '<redacted>...', Array, Resource id #432)
#4 {main}
  thrown in /var/www/html/certificate-expiry-monitor/functions/helpers.php on line 77
```

**Comment by VR44** [comment]
bcmod function is part of the bcmath functions in PHP, how did you install PHP? if you compiled it yourself you need to include the --enable-bcmath flag

**Comment by Beeez** [comment]
> bcmod function is part of the bcmath functions in PHP, how did you install PHP? if you compiled it yourself you need to include the --enable-bcmath flag

I did not compile PHP, just used pre built packages. I just ran yum install php-bcmath and it installed, and i see it in the module list now in php-m. Is there anything else i need to do to enable it or should it work now?

**Comment by Beeez** [comment]
Perfectm everything works now.

**Comment by VR44** [comment]
glad it helped, seems that most package managers (yum/apt/etc) have packaged bcmod into it's own extension
for ubuntu/debian users `sudo apt install php-bcmath` or `sudo apt install php7.x-bcmod` (inputting your php version where required) should also work for them
