### ISSUE TITLE
Don't rely on PHP's mail()

### ISSUE THREAD

**Issue by DavidVentura** [RaymiiOrg/certificate-expiry-monitor#7]
PHP's mail is limited and can't deal with some configurations. I've changed it for PHPMailer (ignoring headers for now) and can make a PR if you are interested.

**Comment by RaymiiOrg** [comment]
I'm not familiair with php's mail limits as compared to phpmailer. What would be the benefit? Can you explain that a bit more?

**Comment by centminmod** [comment]
I would love to see smtp support so you can use with some smtp servers like Mandrill, Sendgrid, Amazon SES (keep sending server ips private) :)

**Comment by DavidVentura** [comment]
I use it to have per-application mailing settings mainly, but listed as main features:

* Send emails with multiple TOs, CCs, BCCs and REPLY-TOs
* Multipart/alternative emails for mail clients that do not read HTML email
* Formatting email correctly is surprisingly difficult. There are myriad overlapping RFCs, requiring tight adherence to horribly complicated formatting and encoding rules - the vast majority of code that you'll find online that uses the mail() function directly is just plain wrong! Please don't be tempted to do it yourself

**Comment by SiamKreative** [comment]
I would recommend using [Mailgun](https://www.mailgun.com/), now that [Mandrill is not free anymore](http://blog.mandrill.com/important-changes-to-mandrill.htm). But it would be good to let each user setup their own API access...
