### ISSUE TITLE
Delete on GET considered harmful

### ISSUE THREAD

**Issue by leighklotz** [RaymiiOrg/certificate-expiry-monitor#9]
Deleting the subscription on HTTP GET is considered harmful.  Instead, consider GET taking you to a confirm page that does a POST to do the delete.
1. Clicking on a link in email mistakenly will remove the subscription with no confirmation.
2. Something or someone else might fetch a web page without the intent to delete.

**Comment by RaymiiOrg** [comment]
If a subscription is removed, the original email address is notified and if required, they can subscribe again. However, merge request is welcome.
